### ISSUE TITLE
Error Initializing Client

### ISSUE THREAD

**Issue by ALEEF02** [top-gg/donatebot-java-api#1]
When I try to initialize the client, I get this error
```
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at Allegiance.threads.ServiceHandlerThread.initServices(ServiceHandlerThread.java:28)
        at Allegiance.threads.ServiceHandlerThread.run(ServiceHandlerThread.java:44)
Caused by: java.lang.NoSuchMethodError: 'io.netty.handler.ssl.SslContextBuilder io.netty.handler.ssl.SslContextBuilder.protocols(java.lang.String[])'
        at org.asynchttpclient.netty.ssl.DefaultSslEngineFactory.buildSslContext(DefaultSslEngineFactory.java:46)
        at org.asynchttpclient.netty.ssl.DefaultSslEngineFactory.init(DefaultSslEngineFactory.java:74)
        at org.asynchttpclient.netty.channel.ChannelManager.<init>(ChannelManager.java:104)
        at org.asynchttpclient.DefaultAsyncHttpClient.<init>(DefaultAsyncHttpClient.java:92)
        at org.asynchttpclient.DefaultAsyncHttpClient.<init>(DefaultAsyncHttpClient.java:74)
        at org.asynchttpclient.Dsl.asyncHttpClient(Dsl.java:28)
        at io.donatebot.api.DBClient.<init>(DBClient.java:22)
```

**Comment by ALEEF02** [comment]
@jczstudios Is there a fix for this?
